### ISSUE TITLE
Font check always passes on Firefox

### ISSUE THREAD

**Issue by joshualiangxy** [bchenghi/browser-fingerprinting#1]
https://github.com/bchenghi/browser-fingerprinting/blob/22c60adc0f35064c9178a9deb403558ebc5d1d7b/basicFingerprinting.js#L17

This line always returns true in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1252821

Is there an implementation that can work for both firefox and chrome?

**Comment by jonahtanjz** [comment]
Should be resolved now by using another method for firefox browsers
